# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fbfd631f904aba27829194a127c787f689e1f5e6c2c2d05f786da79921072d81a6c2fd24f26ba0111191d86d8c749543258ee438adcce87c5bbd887d3f35862c

test:
  secret_key_base: a14e3fb0e35157cae1263d63c3d6e7932184d1b7ce5b39efc77f0314e9037b821882c08d0dcd5594cd8ac6f9ab4b0ab464eaa95cc55f93a685d1727cdc08cfbc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
